# Default values for openvpn.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: jfelten/openvpn-docker
  tag: 1.1.0
  pullPolicy: IfNotPresent
service:
  name: openvpn
  type: NodePort
  externalPort: 443
  internalPort: 443
  nodePort: 30000
resources:
  limits:
    cpu: 300m
    memory: 128Mi
  requests:
    cpu: 300m
    memory: 128Mi
persistence:
  ## openvpn data Persistent Volume Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  #dynamic: 
    #storageClass: "-"
    #accessMode: ReadWriteOnce
    #size: 2M
  ## some clusters, particuarily bare metal, don't use dynamic file storage. The folloing example provisions a volume an in network glsuterfs server.
  ## Replace the static block with config relevant to your system
  static:
    glusterfs:
      endpoints: glusterfs
      path: certs1
      readOnly: false

openvpn:
    # Network allocated for openvpn clients (default: 10.240.0.0).
    OVPN_NETWORK: 10.240.0.0
    # Network subnet allocated for openvpn client (default: 255.255.0.0).
    OVPN_SUBNET:  255.255.0.0
    # Protocol used by openvpn tcp or udp (default: udp).
    OVPN_PROTO: tcp
    # Kubernetes pod network (optional).
    #OVPN_K8S_POD_NETWORK: "10.0.0.0"
    # Kubernetes pod network subnet (optional).
    #OVPN_K8S_POD_SUBNET: "255.0.0.0"
    # Arbitrary lines appended to the end of the server configuration file
    conf: |
      #performance tuning
      tun-mtu 1400 #this value must be lower than that used by cloud provider network - ex GCE is 1460, ec2 9001
      mssfix 1360
      sndbuf 0
      rcvbuf 0
      push "sndbuf 393216"
      push "rcvbuf 393216"
      #max-clients 100
      #client-to-client
      push "dhcp-option DNS 8.8.8.8"

