kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: default
  labels:
    app: {{ template "name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: commandhistory.com/nfs
