
apiVersion: v1
kind: ConfigMap
metadata:
  name: '{{ template "name" . }}'
  labels:
    glusterfs: heketi-configs
    heketi: configs
    app: {{ template "name" . }}
    chart: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  topology.json: |-
    {
      "clusters": [
        {
          "nodes": [
            {
              "node": {
                "hostnames": {
                  "manage": [
                    "gluster1"
                  ],
                  "storage": [
                    "10.10.10.18"
                  ]
                },
                "zone": 1
              },
              "devices": [
                "/dev/vdc",
                "/dev/vdd"
              ]
            },
            {
              "node": {
                "hostnames": {
                  "manage": [
                    "gluster2"
                  ],
                  "storage": [
                    "10.10.10.19"
                  ]
                },
                "zone": 1
              },
              "devices": [
                "/dev/vdc",
                "/dev/vdd"
              ]
            },
            {
              "node": {
                "hostnames": {
                  "manage": [
                    "gluster3"
                  ],
                  "storage": [
                    "10.10.10.17"
                  ]
                },
                "zone": 1
              },
              "devices": [
                "/dev/vdc",
                "/dev/vdd"
              ]
            }
          ]
        }
      ]
    }


  heketi.json: |-
    {
      "_port_comment": "Heketi Server Port Number",
      "port" : "8080",
    
      "_use_auth": "Enable JWT authorization. Please enable for deployment",
      "use_auth" : false,
    
      "_jwt" : "Private keys for access",
      "jwt" : {
        "_admin" : "Admin has access to all APIs",
        "admin" : {
          "key" : "{{ .Values.heketi.key }}"
        },
        "_user" : "User only has access to /volumes endpoint",
        "user" : {
          "key" : "{{ .Values.heketi.key }}"
        }
      },
    
      "_glusterfs_comment": "GlusterFS Configuration",
      "glusterfs" : {
    
        "_executor_comment": "Execute plugin. Possible choices: mock, kubernetes, ssh",
        "executor" : "{{ .Values.heketi.key }}",
    
        "_db_comment": "Database file name",
        "db" : "/var/lib/heketi/heketi.db",
    
        "kubeexec" : {
          "rebalance_on_expansion": true
        },
    
        "sshexec" : {
          "rebalance_on_expansion": true,
          "keyfile" : "/etc/heketi/secrets/ssh-key",
          "port" : "{{ .Values.heketi.ssh_port }}",
          "user" : "{{ .Values.heketi.ssh_user }}"
        }
      },
    
      "backup_db_to_kube_secret": false
    }