apiVersion: v1
kind: ServiceAccount
metadata:
  name: '{{ template "name" . }}'
  labels:
    glusterfs: heketi-sa
    heketi: sa
    app: {{ template "name" . }}
    chart: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    description: Heketi Service Account